### PR TITLE
much cleaner code, new method for swipes, bug fixes, memory leaks fixed

### PR DESCRIPTION
**Pull request by RonMelkhior**

### CODE REVIEW

**Comment by iHeli0s** [comment]
This was one of my first developing projects, and I no longer have time for updates, you are more than welcome to submit it to BigBoss under the same name as an update

**Comment by RonMelkhior** [comment]
I'll do that for sure, but first I need to fix some bug that cause that it's impossible to unlock

**Comment by iHeli0s** [comment]
you could probably just set the gesture recognizers not to conflict with others in the delegate. If I get time I will just remake the whole thing

**Comment by RonMelkhior** [comment]
Yeah I know, I'll do it today.

Sent from my iPhone

On Mar 1, 2012, at 4:27 AM, iHeli0s
reply@reply.github.com
wrote:

**Pull request merged**
